import type { MoodTag, TagCategoryType } from "~/types/diary";

export const tags: Record<TagCategoryType, Array<MoodTag>> = {
  mood: [
    { id: "hap", emoji: "😊", text: "Happy" },
    { id: "sad", emoji: "😢", text: "Sad" },
    { id: "ang", emoji: "😠", text: "Angry" },
    { id: "clm", emoji: "😌", text: "Calm" },
    { id: "anx", emoji: "😨", text: "Anxious" },
    { id: "exc", emoji: "🤩", text: "Excited" },
    { id: "dis", emoji: "😔", text: "Disappointed" },
    { id: "lov", emoji: "🥰", text: "Loved" },
    { id: "neu", emoji: "😐", text: "Neutral" },
    { id: "fru", emoji: "😤", text: "Frustrated" },
    { id: "ovr", emoji: "😭", text: "Overwhelmed" },
    { id: "con", emoji: "😎", text: "Confident" },
    { id: "emb", emoji: "😳", text: "Embarrassed" },
  ],
  act: [
    { id: "wrk", emoji: "💼", text: "Work" },
    { id: "exr", emoji: "🏃‍♂️", text: "Exercise" },
    { id: "cln", emoji: "🧹", text: "Cleaning" },
    { id: "std", emoji: "📚", text: "Studying" },
    { id: "cok", emoji: "🍳", text: "Cooking" },
    { id: "shp", emoji: "🛒", text: "Shopping" },
    { id: "gam", emoji: "🎮", text: "Gaming" },
    { id: "med", emoji: "🧘‍♀️", text: "Meditation" },
    { id: "wrt", emoji: "✍️", text: "Writing" },
    { id: "rdg", emoji: "📖", text: "Reading" },
    { id: "msc", emoji: "🎵", text: "Listening to Music" },
    { id: "soc", emoji: "📱", text: "Social Media" },
    { id: "wlk", emoji: "🚶‍♂️", text: "Walking" },
  ],
  focus: [
    { id: "cmp", emoji: "✅", text: "Completed Task" },
    { id: "pln", emoji: "📅", text: "Planning" },
    { id: "tim", emoji: "⏳", text: "Time Management" },
    { id: "dwp", emoji: "🧠", text: "Deep Work" },
    { id: "prg", emoji: "📈", text: "Progress" },
    { id: "gol", emoji: "🎯", text: "Goal Setting" },
    { id: "dst", emoji: "🔕", text: "Distraction-Free" },
    { id: "tdl", emoji: "📝", text: "To-Do List" },
    { id: "ide", emoji: "💡", text: "Idea Generation" },
    { id: "rtn", emoji: "🔄", text: "Routine" },
    { id: "trk", emoji: "📊", text: "Tracking" },
  ],
  health: [
    { id: "eat", emoji: "🍎", text: "Healthy Eating" },
    { id: "slp", emoji: "😴", text: "Good Sleep" },
    { id: "hyd", emoji: "💧", text: "Hydration" },
    { id: "wrk", emoji: "🏋️‍♀️", text: "Workout" },
    { id: "mnd", emoji: "🧘", text: "Mindfulness" },
    { id: "nat", emoji: "🌿", text: "Nature Time" },
    { id: "scf", emoji: "🛁", text: "Self-Care" },
    { id: "sck", emoji: "🤒", text: "Feeling Sick" },
    { id: "chk", emoji: "🩺", text: "Medical Check" },
    { id: "skn", emoji: "🧴", text: "Skincare" },
    { id: "com", emoji: "🧦", text: "Comfort" },
  ],
  reflect: [
    { id: "srf", emoji: "🪞", text: "Self-Reflection" },
    { id: "jrn", emoji: "📓", text: "Journaling" },
    { id: "ins", emoji: "🔍", text: "Insight" },
    { id: "tht", emoji: "💭", text: "Thoughtful Moment" },
    { id: "rlz", emoji: "🧩", text: "Realization" },
    { id: "big", emoji: "🌌", text: "Big Picture" },
    { id: "con", emoji: "🗣️", text: "Meaningful Conversation" },
    { id: "ipc", emoji: "🧘‍♂️", text: "Inner Peace" },
    { id: "wis", emoji: "📜", text: "Wisdom" },
    { id: "lrn", emoji: "🎓", text: "Learning" },
    { id: "lnk", emoji: "🔗", text: "Connection" },
  ],
};
